const actionTypes = {
  LOADING: "LOADING",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  LOGOUT_ERROR: "LOGOUT_ERROR",
  LOGIN_ERROR: "LOGIN_ERROR",
  SIGNUP: "SIGNUP",
  SIGNUP_ERROR: "SIGNUP_ERROR",
  FORGET_PASSWORD: "FORGET_PASSWORD",
  FORGET_PASSWORD_ERROR: "FORGET_PASSWORD_ERROR",
  SEND_REQUEST: "SEND_REQUEST",
  REQUEST_FAILURE: "REQUEST_FAILURE",
  FETCH_COVER_IMG: "FETCH_COVER_IMG",
  FETCH_POPULAR: "FETCH_POPULAR",
  FETCH_TRENDING: "FETCH_TRENDING",
};

export default actionTypes;
